language: php

php:
  - '7.1'
  - '7.2'

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - 'echo "$TOKEN" | docker login ghcr.io -u "$USERNAME" --password-stdin'
  - 'docker pull ghcr.io/novactive/novadroid:latest'

script:
  - 'docker run --rm -i -v $(pwd):/project ghcr.io/novactive/novadroid:latest check --handlers=javascript,php,stylesheets,yaml --disable-tools=sensiosecuritychecker -vv'
